version: "3.8"
services:
  api:
    build: .
    ports:
      - "6662:6662"
      volumes:
        /home/ubuntu/db:/db
      environment:
        SMS_USERNAME: SEARCHFORME
        SMS_PASSWORD: a@2092002
        SMS_SENDER: SEARCHFORMY
        DB_PATH: /db/test.db


# http://www.oursms.net/api/sendsms.php?username=SEARCHFORME&password=a@2092002&message=Hello there!&numbers=966576692747&sender=SEARCHFORMY&unicode=E&return=json